/*
 * InformaTabelaDisponibilidades.java
 *
 * Created on 11 de Fevereiro de 2007, 19:02
 */

package br.com.kairos.timetabling.formulario.tela;
 

import java.awt.Component;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumn;
import br.com.kairos.timetabling.objetos.*;
import br.com.kairos.timetabling.controle.*;
import java.util.*;
import javax.swing.GroupLayout;
import javax.swing.LayoutStyle;

public class InformaTabelaDisponibilidades extends javax.swing.JDialog{
    private final Horario horario;
    private final ControleHorario controle;
    private final DefaultTableModel modelTabelaDisponibilidades=new DefaultTableModel(){
        public boolean isCellEditable(int rowIndex, int columnIndex) {
            return false;
        }};
    private Integer[] disponibilidades;
    /** Creates new form InformaTabelaDisponibilidades */
    public InformaTabelaDisponibilidades(ControleHorario c,String nomeProfessor) {
        initComponents();
        this.setTitle("Disponibilidades do Professor");
        this.setBounds(100,100, 500, 400);
        this.setModal(true);
        
        this.horario=c.getHorario();
        this.controle=c;
        
        jLabelNomeProfessor.setText(nomeProfessor);
        
        jTableDisponibilidades.setModel(modelTabelaDisponibilidades);
        String[] dias=new String[horario.getDias().length+1];
        String[] diasHorario=horario.getDias();
        dias[0]="Horário";
        System.arraycopy(diasHorario, 0, dias, 1, dias.length - 1);
        modelTabelaDisponibilidades.setColumnCount(dias.length);
        modelTabelaDisponibilidades.setNumRows(horario.getPeriodos());
        modelTabelaDisponibilidades.setColumnIdentifiers(dias);
        Professor professor=controle.getProfessor(nomeProfessor);
        for(int i=1;i<jTableDisponibilidades.getColumnCount();i++){
            jTableDisponibilidades.getColumn(jTableDisponibilidades.getColumnName(i)).setCellRenderer(
                    new JlabelRendererDisponibilidades());
            for(int j=0;j<jTableDisponibilidades.getRowCount();j++){
                modelTabelaDisponibilidades.setValueAt(professor.getDisponibilidade((i*jTableDisponibilidades.getRowCount()+j)-jTableDisponibilidades.getRowCount()),j,i);
            }
            if(i<=jTableDisponibilidades.getRowCount()){
                modelTabelaDisponibilidades.setValueAt(i,i-1,0);
            }
        }
        jTableDisponibilidades.setRowHeight(30);
    }
    
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableDisponibilidades = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jButtonCancelar = new javax.swing.JButton();
        jButtonOK = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabelNomeProfessor = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Tabela de Disponibilidades");
        setAlwaysOnTop(true);
        jTableDisponibilidades.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Title 1", "Title 2"
            }
        ) {
            final boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTableDisponibilidades.setCellSelectionEnabled(true);
        jTableDisponibilidades.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableDisponibilidadesMouseClicked(evt);
            }
        });

        jScrollPane1.setViewportView(jTableDisponibilidades);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12));
        jLabel2.setText("LEGENDA:");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 11));
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/timetabling/formulario/icones/NaoPode.png")));
        jLabel3.setText("- N\u00e2o Pode");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 11));
        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/timetabling/formulario/icones/Pode.png")));
        jLabel4.setText("- Pode");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 11));
        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/timetabling/formulario/icones/Quer.png")));
        jLabel5.setText("- Quer");

        jButtonCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/timetabling/formulario/icones/cancelar.png")));
        jButtonCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCancelarActionPerformed(evt);
            }
        });

        jButtonOK.setIcon(new javax.swing.ImageIcon(getClass().getResource("/timetabling/formulario/icones/salvar.png")));
        jButtonOK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonOKActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14));
        jLabel1.setText("Disponibilidades do professor");

        jLabelNomeProfessor.setFont(new java.awt.Font("Tahoma", 1, 14));
        jLabelNomeProfessor.setForeground(new java.awt.Color(51, 51, 255));
        jLabelNomeProfessor.setText("NomeProfessor");

        // --- Configuração final do Layout do ContentPane ---
        GroupLayout layout = new GroupLayout(getContentPane());
        getContentPane().setLayout(layout);

        layout.setHorizontalGroup(
                layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                        .addGroup(GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(31, 31, 31)
                                .addGroup(layout.createParallelGroup(GroupLayout.Alignment.TRAILING)
                                        .addGroup(layout.createSequentialGroup()
                                                .addComponent(jLabel1, GroupLayout.PREFERRED_SIZE, 209, GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jLabelNomeProfessor, GroupLayout.PREFERRED_SIZE, 238, GroupLayout.PREFERRED_SIZE)
                                                .addGap(45, 45, 45))
                                        .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(GroupLayout.Alignment.TRAILING)
                                                        .addComponent(jScrollPane1, GroupLayout.DEFAULT_SIZE, 431, Short.MAX_VALUE)
                                                        .addGroup(layout.createSequentialGroup()
                                                                .addComponent(jLabel2, GroupLayout.PREFERRED_SIZE, 79, GroupLayout.PREFERRED_SIZE)
                                                                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                                                                .addComponent(jLabel3)
                                                                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                                                                .addComponent(jLabel4)
                                                                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                                                                .addComponent(jLabel5)
                                                                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                                .addComponent(jButtonOK, GroupLayout.PREFERRED_SIZE, 42, GroupLayout.PREFERRED_SIZE)
                                                                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                                                                .addComponent(jButtonCancelar, GroupLayout.PREFERRED_SIZE, 42, GroupLayout.PREFERRED_SIZE)))
                                                .addGap(102, 102, 102)))
                                .addContainerGap())
        );

        layout.setVerticalGroup(
                layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                        .addGroup(GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(layout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel1)
                                        .addComponent(jLabelNomeProfessor))
                                .addGap(26, 26, 26)
                                .addComponent(jScrollPane1, GroupLayout.PREFERRED_SIZE, 211, GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED, 17, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel2)
                                        .addComponent(jLabel3)
                                        .addComponent(jLabel4)
                                        .addComponent(jLabel5)
                                        .addComponent(jButtonCancelar, GroupLayout.PREFERRED_SIZE, 40, GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jButtonOK, GroupLayout.PREFERRED_SIZE, 40, GroupLayout.PREFERRED_SIZE))
                                .addGap(36, 36, 36))
        );
        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    private void jButtonOKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonOKActionPerformed
        Professor prof=null;
        String nomeProfessor =jLabelNomeProfessor.getText();
        disponibilidades=new Integer[(jTableDisponibilidades.getColumnCount()-1)*jTableDisponibilidades.getRowCount()];
        int aux=0;
        prof= controle.getProfessor(nomeProfessor);
        for(int i=1;i<jTableDisponibilidades.getColumnCount();i++){
            for(int j=0;j<jTableDisponibilidades.getRowCount();j++){
                disponibilidades[aux]=(Integer)jTableDisponibilidades.getValueAt(j,i);
                if(disponibilidades[aux]!=0){
                    jTableDisponibilidades.setValueAt(0,j,i);
                }
                aux++;
            }
        }
        prof.addDisponibilidades(disponibilidades);
        this.dispose();
    }//GEN-LAST:event_jButtonOKActionPerformed
    
    private void jButtonCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCancelarActionPerformed
        this.dispose();
    }//GEN-LAST:event_jButtonCancelarActionPerformed
    
    private void jTableDisponibilidadesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableDisponibilidadesMouseClicked
        int linha=jTableDisponibilidades.rowAtPoint(evt.getPoint());
        int coluna=jTableDisponibilidades.columnAtPoint(evt.getPoint());
        int opcao=(Integer)jTableDisponibilidades.getValueAt(linha,coluna);
        if(coluna!=0){
            if(opcao==0){
                jTableDisponibilidades.setValueAt(1,linha,coluna);
            }else{
                if(opcao==1){
                    jTableDisponibilidades.setValueAt(2,linha,coluna);
                }else{
                    jTableDisponibilidades.setValueAt(0,linha,coluna);
                }
            }
        }
    }//GEN-LAST:event_jTableDisponibilidadesMouseClicked
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonCancelar;
    private javax.swing.JButton jButtonOK;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabelNomeProfessor;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableDisponibilidades;
    // End of variables declaration//GEN-END:variables
    
}
