/*
 * ListarDisciplinas.java
 *
 * Created on 22 de Janeiro de 2007, 16:35
 */

package br.com.kairos.timetabling.formulario.tela;

 
import javax.swing.DefaultListModel;
import br.com.kairos.timetabling.controle.ControleHorario;
import br.com.kairos.timetabling.model.*;
import java.util.*;
import javax.swing.GroupLayout;
import javax.swing.LayoutStyle;

public class ListarDisciplinas extends javax.swing.JDialog {
    DefaultListModel modelListDisciplinas;
    ArrayList disciplinas;
    Disciplina disciplina;
    TreeMap professores;
    Iterator indice;
    ControleHorario controle;
    /**
     * Creates new form ListarDisciplinas
     */
    public ListarDisciplinas(ControleHorario cHorario) {
        initComponents();
        this.setTitle("Lista de Disciplinas Cadastradas");
        this.setBounds(150,100,650,450);
        this.setModal(true);
        jLabel2.setVisible(false);
        jLabel4.setVisible(false);
        jLabel5.setVisible(false);
        jLabel6.setVisible(false);
        jLabel7.setVisible(false);
        jLabelNomeDisciplina.setText("");
        jLabelSigla.setText("");
        jLabelCargaHoraria.setText("");
        jLabelNomeProfessor.setText("");
        jLabelSemestre.setText("");
        jButtonAlterar.setVisible(false);
        jButtonExcluir.setVisible(false);
        jCheckBoxPrioridade.setVisible(false);
        jLabelCor.setText("");
        jLabelCor.setVisible(false);
        
        this.controle=cHorario;
        
        modelListDisciplinas = new DefaultListModel();
        jListDisciplinas.setModel(modelListDisciplinas);
        
        disciplinas=controle.getTodasDisciplinas();
        indice=disciplinas.iterator();
        while(indice.hasNext()){
            disciplina=(Disciplina)indice.next();
            modelListDisciplinas.addElement(disciplina.getNome());
        }
        disciplina=(Disciplina)disciplinas.get(0);
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {
        jScrollPane1 = new javax.swing.JScrollPane();
        jListDisciplinas = new javax.swing.JList();
        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabelNomeDisciplina = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabelCargaHoraria = new javax.swing.JLabel();
        jLabelNomeProfessor = new javax.swing.JLabel();
        jLabelSigla = new javax.swing.JLabel();
        jButtonExcluir = new javax.swing.JButton();
        jButtonAlterar = new javax.swing.JButton();
        jCheckBoxPrioridade = new javax.swing.JCheckBox();
        jLabel7 = new javax.swing.JLabel();
        jLabelSemestre = new javax.swing.JLabel();
        jLabelCor = new javax.swing.JLabel();
        jButtonOK = new javax.swing.JButton();
        jLabelAdicionaDisciplina = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        jListDisciplinas.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jListDisciplinasKeyReleased(evt);
            }
        });
        jListDisciplinas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jListDisciplinasMouseClicked(evt);
            }
        });

        jScrollPane1.setViewportView(jListDisciplinas);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12));
        jLabel1.setText("Lista de Disciplinas:");

        jPanel1.setLayout(null);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Dados da Disciplina", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 10)));
        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12));
        jLabel2.setText("Nome da Disciplina:");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(20, 40, 129, 15);
        jLabel2.getAccessibleContext().setAccessibleParent(jPanel1);

        jLabelNomeDisciplina.setText("Disciplina");
        jPanel1.add(jLabelNomeDisciplina);
        jLabelNomeDisciplina.setBounds(180, 40, 230, 14);
        jLabelNomeDisciplina.getAccessibleContext().setAccessibleParent(jPanel1);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12));
        jLabel4.setText("Sigla:");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(20, 70, 45, 15);
        jLabel4.getAccessibleContext().setAccessibleParent(jPanel1);

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 12));
        jLabel6.setText("Professor:");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(20, 160, 120, 15);
        jLabel6.getAccessibleContext().setAccessibleParent(jPanel1);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 12));
        jLabel5.setText("Carga Hor\u00e1ria:");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(20, 100, 101, 15);
        jLabel5.getAccessibleContext().setAccessibleParent(jPanel1);

        jLabelCargaHoraria.setText("Carga Hor\u00e1ria");
        jPanel1.add(jLabelCargaHoraria);
        jLabelCargaHoraria.setBounds(180, 100, 157, 14);
        jLabelCargaHoraria.getAccessibleContext().setAccessibleParent(jPanel1);

        jLabelNomeProfessor.setFont(new java.awt.Font("Tahoma", 1, 11));
        jLabelNomeProfessor.setForeground(new java.awt.Color(0, 0, 255));
        jLabelNomeProfessor.setText("Professor");
        jLabelNomeProfessor.setToolTipText("Disponibilidades do professor");
        jLabelNomeProfessor.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelNomeProfessorMouseClicked(evt);
            }
        });

        jPanel1.add(jLabelNomeProfessor);
        jLabelNomeProfessor.setBounds(180, 160, 230, 14);
        jLabelNomeProfessor.getAccessibleContext().setAccessibleParent(jPanel1);

        jLabelSigla.setText("Sigla");
        jPanel1.add(jLabelSigla);
        jLabelSigla.setBounds(180, 70, 57, 14);
        jLabelSigla.getAccessibleContext().setAccessibleParent(jPanel1);

        jButtonExcluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/timetabling/formulario/icones/NaoPode.png")));
        jButtonExcluir.setToolTipText("Excluir disciplina");
        jButtonExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonExcluirActionPerformed(evt);
            }
        });

        jPanel1.add(jButtonExcluir);
        jButtonExcluir.setBounds(230, 240, 70, 40);

        jButtonAlterar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/timetabling/formulario/icones/Pode.png")));
        jButtonAlterar.setToolTipText("Alterar disciplina");
        jButtonAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAlterarActionPerformed(evt);
            }
        });

        jPanel1.add(jButtonAlterar);
        jButtonAlterar.setBounds(150, 240, 70, 40);

        jCheckBoxPrioridade.setText("Prioridade do professor para a disciplina");
        jCheckBoxPrioridade.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        jCheckBoxPrioridade.setEnabled(false);
        jCheckBoxPrioridade.setMargin(new java.awt.Insets(0, 0, 0, 0));
        jPanel1.add(jCheckBoxPrioridade);
        jCheckBoxPrioridade.setBounds(20, 190, 250, 15);

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 12));
        jLabel7.setText("Semestre:");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(20, 130, 83, 15);

        jLabelSemestre.setText("Semestre");
        jPanel1.add(jLabelSemestre);
        jLabelSemestre.setBounds(180, 130, 57, 14);

        jLabelCor.setText("Cor");
        jPanel1.add(jLabelCor);
        jLabelCor.setBounds(390, 10, 20, 20);

        jButtonOK.setIcon(new javax.swing.ImageIcon(getClass().getResource("/timetabling/formulario/icones/salvar.png")));
        jButtonOK.setToolTipText("OK");
        jButtonOK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonOKActionPerformed(evt);
            }
        });

        jLabelAdicionaDisciplina.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelAdicionaDisciplina.setIcon(new javax.swing.ImageIcon(getClass().getResource("/timetabling/formulario/icones/+.png")));
        jLabelAdicionaDisciplina.setToolTipText("Adcionar Professor");
        jLabelAdicionaDisciplina.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelAdicionaDisciplinaMouseClicked(evt);
            }
        });

        GroupLayout layout = new GroupLayout(getContentPane());
        getContentPane().setLayout(layout);

        layout.setHorizontalGroup(
                layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                        .addGroup(GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(GroupLayout.Alignment.TRAILING)
                                        .addGroup(layout.createSequentialGroup()
                                                .addContainerGap()
                                                .addComponent(jButtonOK, GroupLayout.PREFERRED_SIZE, 40, GroupLayout.PREFERRED_SIZE))
                                        .addGroup(layout.createSequentialGroup()
                                                .addGap(18, 18, 18)
                                                .addGroup(layout.createParallelGroup(GroupLayout.Alignment.TRAILING)
                                                        .addGroup(layout.createSequentialGroup()
                                                                .addComponent(jLabel1)
                                                                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED, 62, Short.MAX_VALUE)
                                                                .addComponent(jLabelAdicionaDisciplina))
                                                        .addComponent(jScrollPane1, GroupLayout.DEFAULT_SIZE, 193, Short.MAX_VALUE))
                                                .addGap(17, 17, 17)
                                                .addComponent(jPanel1, GroupLayout.PREFERRED_SIZE, 422, GroupLayout.PREFERRED_SIZE)))
                                .addContainerGap())
        );

        layout.setVerticalGroup(
                layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(layout.createParallelGroup(GroupLayout.Alignment.LEADING, false)
                                        .addGroup(layout.createSequentialGroup()
                                                .addGap(11, 11, 11)
                                                .addComponent(jLabelAdicionaDisciplina)
                                                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED))
                                        .addGroup(GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                .addComponent(jLabel1)
                                                .addGap(15, 15, 15)))
                                .addGroup(layout.createParallelGroup(GroupLayout.Alignment.TRAILING)
                                        .addComponent(jPanel1, GroupLayout.DEFAULT_SIZE, 303, Short.MAX_VALUE)
                                        .addComponent(jScrollPane1, GroupLayout.DEFAULT_SIZE, 303, Short.MAX_VALUE))
                                .addGap(19, 19, 19)
                                .addComponent(jButtonOK, GroupLayout.PREFERRED_SIZE, 40, GroupLayout.PREFERRED_SIZE)
                                .addContainerGap())
        );
        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jListDisciplinasKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jListDisciplinasKeyReleased
        String nomeDisciplina= jListDisciplinas.getSelectedValue();
        indice=disciplinas.iterator();
        while(indice.hasNext()&&!(disciplina.getNome()).equals(nomeDisciplina)){
            disciplina=(Disciplina)indice.next();
        }
        jLabel2.setVisible(true);
        jLabel4.setVisible(true);
        jLabel5.setVisible(true);
        jLabel6.setVisible(true);
        jLabel7.setVisible(true);
        jLabelCor.setVisible(true);
        jLabelNomeDisciplina.setText(disciplina.getNome());
        jLabelCor.setBackground(disciplina.getCor());
        jLabelCor.setOpaque(true);
        jLabelSigla.setText(disciplina.getSigla());
        jLabelCargaHoraria.setText(disciplina.getCargaHorariaSemanal()+"");
        jLabelNomeProfessor.setText(disciplina.getNomeProfessor());
        jLabelSemestre.setText(disciplina.getSemestre());
        jButtonAlterar.setVisible(true);
        jButtonExcluir.setVisible(true);
        jCheckBoxPrioridade.setSelected(disciplina.getPrioridade());
        jCheckBoxPrioridade.setVisible(true);
    }//GEN-LAST:event_jListDisciplinasKeyReleased
    
    private void jLabelAdicionaDisciplinaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelAdicionaDisciplinaMouseClicked
        CadastroDisciplinas cadastroDisciplina=new CadastroDisciplinas(controle);
        cadastroDisciplina.setVisible(true);
        modelListDisciplinas.removeAllElements();
        disciplinas=controle.getTodasDisciplinas();
        indice=disciplinas.iterator();
        while(indice.hasNext()){
            disciplina=(Disciplina)indice.next();
            modelListDisciplinas.addElement(disciplina.getNome());
        }
        disciplina=(Disciplina)disciplinas.get(0);
    }//GEN-LAST:event_jLabelAdicionaDisciplinaMouseClicked
    
    private void jLabelNomeProfessorMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelNomeProfessorMouseClicked
        String nomeProfessor=jLabelNomeProfessor.getText();
        InformaTabelaDisponibilidades dispProfessor=new InformaTabelaDisponibilidades(controle,nomeProfessor);
        dispProfessor.setVisible(true);
    }//GEN-LAST:event_jLabelNomeProfessorMouseClicked
    
    private void jListDisciplinasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jListDisciplinasMouseClicked
        String nomeDisciplina= jListDisciplinas.getSelectedValue();
        indice=disciplinas.iterator();
        while(indice.hasNext()&&!(disciplina.getNome()).equals(nomeDisciplina)){
            disciplina=(Disciplina)indice.next();
        }
        jLabel2.setVisible(true);
        jLabel4.setVisible(true);
        jLabel5.setVisible(true);
        jLabel6.setVisible(true);
        jLabel7.setVisible(true);
        jLabelCor.setVisible(true);
        jLabelNomeDisciplina.setText(disciplina.getNome());
        jLabelCor.setBackground(disciplina.getCor());
        jLabelCor.setOpaque(true);
        jLabelSigla.setText(disciplina.getSigla());
        jLabelCargaHoraria.setText(disciplina.getCargaHorariaSemanal()+"");
        jLabelNomeProfessor.setText(disciplina.getNomeProfessor());
        jLabelSemestre.setText(disciplina.getSemestre());
        jButtonAlterar.setVisible(true);
        jButtonExcluir.setVisible(true);
        jCheckBoxPrioridade.setSelected(disciplina.getPrioridade());
        jCheckBoxPrioridade.setVisible(true);
    }//GEN-LAST:event_jListDisciplinasMouseClicked
    
    private void jButtonAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAlterarActionPerformed
        String nomeDisciplina= jListDisciplinas.getSelectedValue();
        indice=disciplinas.iterator();
        while(indice.hasNext()&&!(disciplina.getNome()).equals(nomeDisciplina)){
            disciplina=(Disciplina)indice.next();
        }
        CadastroDisciplinas cadastroDisciplina=new CadastroDisciplinas(controle,disciplina);
        cadastroDisciplina.setVisible(true);
        int posicao=modelListDisciplinas.indexOf(disciplina.getNome());
        modelListDisciplinas.removeElement(disciplina.getNome());
        Disciplina d=(Disciplina)controle.getTodasDisciplinas().get(disciplina.getCodigoGA()-1);
        modelListDisciplinas.insertElementAt(d.getNome(),posicao);
        jListDisciplinas.setSelectedIndex(posicao);
        nomeDisciplina= jListDisciplinas.getSelectedValue();
        indice=disciplinas.iterator();
        while(indice.hasNext()&&!(disciplina.getNome()).equals(nomeDisciplina)){
            disciplina=(Disciplina)indice.next();
        }
        jLabel2.setVisible(true);
        jLabel4.setVisible(true);
        jLabel5.setVisible(true);
        jLabel6.setVisible(true);
        jLabel7.setVisible(true);
        jLabelCor.setVisible(true);
        jLabelNomeDisciplina.setText(disciplina.getNome());
        jLabelCor.setBackground(disciplina.getCor());
        jLabelCor.setOpaque(true);
        jLabelSigla.setText(disciplina.getSigla());
        jLabelCargaHoraria.setText(disciplina.getCargaHorariaSemanal()+"");
        jLabelNomeProfessor.setText(disciplina.getNomeProfessor());
        jLabelSemestre.setText(disciplina.getSemestre());
        jButtonAlterar.setVisible(true);
        jButtonExcluir.setVisible(true);
        jCheckBoxPrioridade.setSelected(disciplina.getPrioridade());
        jCheckBoxPrioridade.setVisible(true);
    }//GEN-LAST:event_jButtonAlterarActionPerformed
    
    private void jButtonExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonExcluirActionPerformed
        String nomeDisciplina= jListDisciplinas.getSelectedValue();
        indice=disciplinas.iterator();
        while(indice.hasNext()&&!(disciplina.getNome()).equals(nomeDisciplina)){
            disciplina=(Disciplina)indice.next();
        }
        controle.getTodasDisciplinas().remove(disciplina);
        modelListDisciplinas.removeElement(nomeDisciplina);
        jLabel2.setVisible(false);
        jLabel4.setVisible(false);
        jLabel5.setVisible(false);
        jLabel6.setVisible(false);
        jLabel7.setVisible(false);
        jLabelCor.setVisible(false);
        jLabelNomeDisciplina.setText("");
        jLabelSigla.setText("");
        jLabelCargaHoraria.setText("");
        jLabelNomeProfessor.setText("");
        jLabelSemestre.setText("");
        jButtonAlterar.setVisible(false);
        jButtonExcluir.setVisible(false);
        jCheckBoxPrioridade.setVisible(false);
    }//GEN-LAST:event_jButtonExcluirActionPerformed
    
    private void jButtonOKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonOKActionPerformed
        this.dispose();
    }//GEN-LAST:event_jButtonOKActionPerformed
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAlterar;
    private javax.swing.JButton jButtonExcluir;
    private javax.swing.JButton jButtonOK;
    private javax.swing.JCheckBox jCheckBoxPrioridade;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabelAdicionaDisciplina;
    private javax.swing.JLabel jLabelCargaHoraria;
    private javax.swing.JLabel jLabelCor;
    private javax.swing.JLabel jLabelNomeDisciplina;
    private javax.swing.JLabel jLabelNomeProfessor;
    private javax.swing.JLabel jLabelSemestre;
    private javax.swing.JLabel jLabelSigla;
    private javax.swing.JList<String> jListDisciplinas;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
    
}
